#Log Level ############################################################################################
#LEVEL: TRACE > DEBUG > INFO > WARN > ERROR
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.ksnet=WARNe

#jdbcTemplate sql log
logging.level.org.springframework.jdbc=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN

# DATABASE #################################################################################################
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.hibernate.ddl-auto=none

# Real Environment Setting #################################################################################
# Informix Real Server(mst02_tcp) JDBC
spring.datasource.url=jdbc:informix-sqli://172.25.1.21:3002/ksnet:INFORMIXSERVER=mst02_tcp
spring.datasource.username=username_1234
spring.datasource.password=password_1234
spring.datasource.driver-class-name=com.informix.jdbc.IfxDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.InformixDialect
spring.datasource.hikari.connection-test-query=SELECT * FROM dual
#spring.datasource.jndi-name=java:/comp/env/pgims_mst02_pool

## 파라메터 --COUNTRY=ALL --YEAR=2025 ###########
COUNTRY-CODE=
YEAR=
ONLY-HOLIDAY=false

