spring.application.name=MakeCalendar
spring.profiles.active=dev

#Log Level ############################################################################################
#LEVEL: TRACE > DEBUG > INFO > WARN > ERROR
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.ksnet=WARN

#jdbcTemplate sql log
logging.level.org.springframework.jdbc=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO

# DATABASE #################################################################################################
spring.jpa.properties.hibernate.show_sql=false

# Real Environment Setting #################################################################################
# Informix Real Server(mst02_tcp) JDBC
#spring.datasource.url=jdbc:informix-sqli://172.25.1.21:3002/ksnet:INFORMIXSERVER=mst02_tcp
#spring.datasource.username=username_1234
#spring.datasource.password=password_1234
#spring.datasource.driver-class-name=com.informix.jdbc.IfxDriver
#spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.InformixDialect
#spring.datasource.hikari.connection-test-query=SELECT * FROM dual;
#spring.datasource.jndi-name=java:/comp/env/pgims_mst02_pool

#Scrapping URL
ksnet.pginfo.time-and-date.holiday.url=https://www.timeanddate.com/holidays/

#API URL
# Global Holiday API
ksnet.pginfo.date-nager-at.url=https://date.nager.at/api/v3/PublicHolidays/
# China Holiday API
ksnet.pginfo.timor-tech.url=https://timor.tech/api/holiday/year/

## 파라메터 --COUNTRY=ALL --YEAR=2025 ###########
COUNTRY-CODE=
YEAR=


