#Log Level ############################################################################################
#LEVEL: TRACE > DEBUG > INFO > WARN > ERROR
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.ksnet=INFO

#jdbcTemplate sql log
logging.level.org.springframework.jdbc=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=DEBUG

# DATABASE #################################################################################################
spring.jpa.properties.hibernate.show_sql=false

# H2Database JDBC
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=none

## 파라메터 --COUNTRY=ALL --YEAR=2025 ###########
COUNTRY-CODE=
YEAR=
ONLY-HOLIDAY=true