spring.application.name=MakeCalendar
spring.profiles.active=dev

#Scrapping URL
ksnet.pginfo.time-and-date.holiday.url=https://www.timeanddate.com/holidays/

#API URL
# Global Holiday API
ksnet.pginfo.date-nager-at.url=https://date.nager.at/api/v3/PublicHolidays/
# China Holiday API
ksnet.pginfo.timor-tech.url=https://timor.tech/api/holiday/year/

ksnet.pginfo.time-end-date.api.url=https://api.xmltime.com/holidays?version=3&accesskey=%s&signature=%s&country=%s&year=%s&timestamp=%s
ksnet.pginfo.time-end-date.access-key=UceSNRjQoW
ksnet.pginfo.time-end-date.secret-key=n09JT151vixJH2ek9yAv

## 파라메터 --COUNTRY=ALL --YEAR=2025 ###########
COUNTRY-CODE=
YEAR=
ONLY-HOLIDAY=false

